version: '3'
services:
  gemini:
    build: .
    volumes:
      - ./repositories:/repositories
      - ./query:/query
    environment:
      HOST: scylla
      BBLFSH_HOST: bblfshd
      FEATURES_EXTRACTOR_HOST: featurext
    ports:
      - '4040:4040'

  scylla:
    image: scylladb/scylla:2.0.0
    volumes:
      - /var/lib/scylla
    command:
      - '--broadcast-address'
      - '127.0.0.1'
      - '--listen-address'
      - '0.0.0.0'
      - '--broadcast-rpc-address'
      - '127.0.0.1'
      - '--memory'
      - '2G'
    ports:
      - '9042:9042'

  featurext:
    build:
      context: .
      dockerfile: FE.Dockerfile
    environment:
      PYTHONHASHSEED: '0'

  bblfshd:
    image: bblfsh/bblfshd:v2.11.0-drivers
    privileged: true
