#!/bin/bash
# Convenience script to query for a similar files of a given file

E_BUILD_FAILED=142

version=$(grep "version :=" build.sbt | cut -d'=' -f 2 | tr -d ' ' | tr -d '"')
jar="target/gemini-uber.jar"
deps_jar="target/gemini-assembly-${version}-deps.jar"

build_command="./sbt assembly"
build_deps_command="./sbt assemblyPackageDependency"

current_dir="$(dirname "$0")"
app_class="tech.sourced.gemini.cmd.QueryApp"

hash java >/dev/null 2>&1 || { echo "Please install Java" >&2; exit 1; }

if [[ ! -f "${deps_jar}" ]]; then
    echo "${deps_jar} not found. Running build '${build_deps_command}'"
    if ! $build_deps_command ; then
        exit "${E_BUILD_FAILED}"
    fi
fi

if [[ ! -f "${jar}" ]]; then
    echo "${jar} not found. Running build '${build_command}'"
    if ! $build_command ; then
        exit "${E_BUILD_FAILED}"
    fi
fi

source "${current_dir}/scripts/common_params.sh"

exec java -cp "${jar}:${deps_jar}" "${app_class}" "${COMMAND_PARAMS[@]}"
