#!/bin/bash
# Convenience script to query for a similar files for a single file

E_BUILD_FAILED=142

version=$(grep "version :=" build.sbt | cut -d'=' -f 2 | tr -d ' ' | tr -d '"')
jar="target/gemini-${version}.jar"
build_command="./sbt package"
current_dir="$(dirname "$0")"

app_class="tech.sourced.gemini.QueryApp"

hash java >/dev/null 2>&1 || { echo "Please install Java" >&2; exit 1; }

if [[ ! -f "${jar}" ]]; then
    echo "${jar} not found. Running build '${build_command}'"
    if ! $build_command ; then
        exit "${E_BUILD_FAILED}"
    fi
fi

source "$current_dir/scripts/common_params.sh"

#exec java -cp "${jar}" "${app_class}" $@
exec ./sbt --warn "run-main ${app_class} ${COMMAND_PARAMS[*]}"
