#!/bin/bash
# Convenience script to find all similar files among already hashed repositories

E_BUILD_FAILED=142

jar="target/gemini-uber.jar"
build_command="./sbt assembly"
current_dir="$(dirname "$0")"

app_class="tech.sourced.gemini.cmd.ReportApp"

hash java >/dev/null 2>&1 || { echo "Please install Java" >&2; exit 1; }
hash python3 >/dev/null 2>&1 || { echo "Please install python3" >&2; exit 1; }

if [[ ! -f "${jar}" ]]; then
    echo "${jar} not found. Running build '${build_command}'"
    if ! $build_command ; then
        exit "${E_BUILD_FAILED}"
    fi
fi

source "${current_dir}/scripts/common_params.sh"

exec java -cp "${jar}" "${app_class}" $@
