#!/bin/bash
# Convenience script to find duplicated files among hashed repositories that already exists in certain repository

E_BUILD_FAILED=142

jar="target/gemini-0.0.1-SNAPSHOT.jar"
build_command="./sbt package"

app_class="tech.sourced.gemini.ReportSparkApp"

hash java >/dev/null 2>&1 || { echo "Please install Java" >&2; exit 1; }

if [[ ! -f "${jar}" ]]; then
    echo "${jar} not found. Running build '${build_command}'"
    if ! $build_command ; then
        exit "${E_BUILD_FAILED}"
    fi
fi

exec ./sbt "run-main ${app_class} $*"

