// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package tech.sourced.featurext

object ServiceProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    com.google.protobuf.GogoProto,
    gopkg.in.bblfsh.sdk.v1.uast.GeneratedProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_]] = Seq(
    tech.sourced.featurext.IdentifiersRequest,
    tech.sourced.featurext.LiteralsRequest,
    tech.sourced.featurext.Uast2seqRequest,
    tech.sourced.featurext.Feature,
    tech.sourced.featurext.FeaturesReply
  )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.Seq(
  """Cg1zZXJ2aWNlLnByb3RvEhZ0ZWNoLnNvdXJjZWQuZmVhdHVyZXh0Gi1naXRodWIuY29tL2dvZ28vcHJvdG9idWYvZ29nb3Byb
  3RvL2dvZ28ucHJvdG8aK2dvcGtnLmluL2JibGZzaC9zZGsudjEvdWFzdC9nZW5lcmF0ZWQucHJvdG8irQEKEklkZW50aWZpZXJzU
  mVxdWVzdBI1CgR1YXN0GAEgASgLMiEuZ29wa2cuaW4uYmJsZnNoLnNkay52MS51YXN0Lk5vZGVSBHVhc3QSKgoQZG9jZnJlcVRoc
  mVzaG9sZBgCIAEoBVIQZG9jZnJlcVRocmVzaG9sZBIWCgZ3ZWlnaHQYAyABKAVSBndlaWdodBIcCglzcGxpdFN0ZW0YBCABKAhSC
  XNwbGl0U3RlbSKMAQoPTGl0ZXJhbHNSZXF1ZXN0EjUKBHVhc3QYASABKAsyIS5nb3BrZy5pbi5iYmxmc2guc2RrLnYxLnVhc3QuT
  m9kZVIEdWFzdBIqChBkb2NmcmVxVGhyZXNob2xkGAIgASgFUhBkb2NmcmVxVGhyZXNob2xkEhYKBndlaWdodBgDIAEoBVIGd2VpZ
  2h0IowBCg9VYXN0MnNlcVJlcXVlc3QSNQoEdWFzdBgBIAEoCzIhLmdvcGtnLmluLmJibGZzaC5zZGsudjEudWFzdC5Ob2RlUgR1Y
  XN0EioKEGRvY2ZyZXFUaHJlc2hvbGQYAiABKAVSEGRvY2ZyZXFUaHJlc2hvbGQSFgoGd2VpZ2h0GAMgASgFUgZ3ZWlnaHQiNQoHR
  mVhdHVyZRISCgRuYW1lGAEgASgJUgRuYW1lEhYKBndlaWdodBgCIAEoAlIGd2VpZ2h0IkwKDUZlYXR1cmVzUmVwbHkSOwoIZmVhd
  HVyZXMYASADKAsyHy50ZWNoLnNvdXJjZWQuZmVhdHVyZXh0LkZlYXR1cmVSCGZlYXR1cmVzMrICChBGZWF0dXJlRXh0cmFjdG9yE
  mIKC0lkZW50aWZpZXJzEioudGVjaC5zb3VyY2VkLmZlYXR1cmV4dC5JZGVudGlmaWVyc1JlcXVlc3QaJS50ZWNoLnNvdXJjZWQuZ
  mVhdHVyZXh0LkZlYXR1cmVzUmVwbHkiABJcCghMaXRlcmFscxInLnRlY2guc291cmNlZC5mZWF0dXJleHQuTGl0ZXJhbHNSZXF1Z
  XN0GiUudGVjaC5zb3VyY2VkLmZlYXR1cmV4dC5GZWF0dXJlc1JlcGx5IgASXAoIVWFzdDJzZXESJy50ZWNoLnNvdXJjZWQuZmVhd
  HVyZXh0LlVhc3Qyc2VxUmVxdWVzdBolLnRlY2guc291cmNlZC5mZWF0dXJleHQuRmVhdHVyZXNSZXBseSIAYgZwcm90bzM="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
      com.google.protobuf.GogoProto.javaDescriptor,
      gopkg.in.bblfsh.sdk.v1.uast.GeneratedProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}