// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO2

package com.google.protobuf.gogo

object GogoProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    com.google.protobuf.descriptor.DescriptorProtoCompanion
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_]] = Seq.empty
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.Seq(
  """Ci1naXRodWIuY29tL2dvZ28vcHJvdG9idWYvZ29nb3Byb3RvL2dvZ28ucHJvdG8SCWdvZ29wcm90bxogZ29vZ2xlL3Byb3RvY
  nVmL2Rlc2NyaXB0b3IucHJvdG86TgoTZ29wcm90b19lbnVtX3ByZWZpeBIcLmdvb2dsZS5wcm90b2J1Zi5FbnVtT3B0aW9ucxix5
  AMgASgIUhFnb3Byb3RvRW51bVByZWZpeDpSChVnb3Byb3RvX2VudW1fc3RyaW5nZXISHC5nb29nbGUucHJvdG9idWYuRW51bU9wd
  GlvbnMYxeQDIAEoCFITZ29wcm90b0VudW1TdHJpbmdlcjpDCg1lbnVtX3N0cmluZ2VyEhwuZ29vZ2xlLnByb3RvYnVmLkVudW1Pc
  HRpb25zGMbkAyABKAhSDGVudW1TdHJpbmdlcjpHCg9lbnVtX2N1c3RvbW5hbWUSHC5nb29nbGUucHJvdG9idWYuRW51bU9wdGlvb
  nMYx+QDIAEoCVIOZW51bUN1c3RvbW5hbWU6OgoIZW51bWRlY2wSHC5nb29nbGUucHJvdG9idWYuRW51bU9wdGlvbnMYyOQDIAEoC
  FIIZW51bWRlY2w6VgoUZW51bXZhbHVlX2N1c3RvbW5hbWUSIS5nb29nbGUucHJvdG9idWYuRW51bVZhbHVlT3B0aW9ucxjRgwQgA
  SgJUhNlbnVtdmFsdWVDdXN0b21uYW1lOk4KE2dvcHJvdG9fZ2V0dGVyc19hbGwSHC5nb29nbGUucHJvdG9idWYuRmlsZU9wdGlvb
  nMYmewDIAEoCFIRZ29wcm90b0dldHRlcnNBbGw6VQoXZ29wcm90b19lbnVtX3ByZWZpeF9hbGwSHC5nb29nbGUucHJvdG9idWYuR
  mlsZU9wdGlvbnMYmuwDIAEoCFIUZ29wcm90b0VudW1QcmVmaXhBbGw6UAoUZ29wcm90b19zdHJpbmdlcl9hbGwSHC5nb29nbGUuc
  HJvdG9idWYuRmlsZU9wdGlvbnMYm+wDIAEoCFISZ29wcm90b1N0cmluZ2VyQWxsOkoKEXZlcmJvc2VfZXF1YWxfYWxsEhwuZ29vZ
  2xlLnByb3RvYnVmLkZpbGVPcHRpb25zGJzsAyABKAhSD3ZlcmJvc2VFcXVhbEFsbDo5CghmYWNlX2FsbBIcLmdvb2dsZS5wcm90b
  2J1Zi5GaWxlT3B0aW9ucxid7AMgASgIUgdmYWNlQWxsOkEKDGdvc3RyaW5nX2FsbBIcLmdvb2dsZS5wcm90b2J1Zi5GaWxlT3B0a
  W9ucxie7AMgASgIUgtnb3N0cmluZ0FsbDpBCgxwb3B1bGF0ZV9hbGwSHC5nb29nbGUucHJvdG9idWYuRmlsZU9wdGlvbnMYn+wDI
  AEoCFILcG9wdWxhdGVBbGw6QQoMc3RyaW5nZXJfYWxsEhwuZ29vZ2xlLnByb3RvYnVmLkZpbGVPcHRpb25zGKDsAyABKAhSC3N0c
  mluZ2VyQWxsOj8KC29ubHlvbmVfYWxsEhwuZ29vZ2xlLnByb3RvYnVmLkZpbGVPcHRpb25zGKHsAyABKAhSCm9ubHlvbmVBbGw6O
  woJZXF1YWxfYWxsEhwuZ29vZ2xlLnByb3RvYnVmLkZpbGVPcHRpb25zGKXsAyABKAhSCGVxdWFsQWxsOkcKD2Rlc2NyaXB0aW9uX
  2FsbBIcLmdvb2dsZS5wcm90b2J1Zi5GaWxlT3B0aW9ucxim7AMgASgIUg5kZXNjcmlwdGlvbkFsbDo/Cgt0ZXN0Z2VuX2FsbBIcL
  mdvb2dsZS5wcm90b2J1Zi5GaWxlT3B0aW9ucxin7AMgASgIUgp0ZXN0Z2VuQWxsOkEKDGJlbmNoZ2VuX2FsbBIcLmdvb2dsZS5wc
  m90b2J1Zi5GaWxlT3B0aW9ucxio7AMgASgIUgtiZW5jaGdlbkFsbDpDCg1tYXJzaGFsZXJfYWxsEhwuZ29vZ2xlLnByb3RvYnVmL
  kZpbGVPcHRpb25zGKnsAyABKAhSDG1hcnNoYWxlckFsbDpHCg91bm1hcnNoYWxlcl9hbGwSHC5nb29nbGUucHJvdG9idWYuRmlsZ
  U9wdGlvbnMYquwDIAEoCFIOdW5tYXJzaGFsZXJBbGw6UAoUc3RhYmxlX21hcnNoYWxlcl9hbGwSHC5nb29nbGUucHJvdG9idWYuR
  mlsZU9wdGlvbnMYq+wDIAEoCFISc3RhYmxlTWFyc2hhbGVyQWxsOjsKCXNpemVyX2FsbBIcLmdvb2dsZS5wcm90b2J1Zi5GaWxlT
  3B0aW9ucxis7AMgASgIUghzaXplckFsbDpZChlnb3Byb3RvX2VudW1fc3RyaW5nZXJfYWxsEhwuZ29vZ2xlLnByb3RvYnVmLkZpb
  GVPcHRpb25zGK3sAyABKAhSFmdvcHJvdG9FbnVtU3RyaW5nZXJBbGw6SgoRZW51bV9zdHJpbmdlcl9hbGwSHC5nb29nbGUucHJvd
  G9idWYuRmlsZU9wdGlvbnMYruwDIAEoCFIPZW51bVN0cmluZ2VyQWxsOlAKFHVuc2FmZV9tYXJzaGFsZXJfYWxsEhwuZ29vZ2xlL
  nByb3RvYnVmLkZpbGVPcHRpb25zGK/sAyABKAhSEnVuc2FmZU1hcnNoYWxlckFsbDpUChZ1bnNhZmVfdW5tYXJzaGFsZXJfYWxsE
  hwuZ29vZ2xlLnByb3RvYnVmLkZpbGVPcHRpb25zGLDsAyABKAhSFHVuc2FmZVVubWFyc2hhbGVyQWxsOlsKGmdvcHJvdG9fZXh0Z
  W5zaW9uc19tYXBfYWxsEhwuZ29vZ2xlLnByb3RvYnVmLkZpbGVPcHRpb25zGLHsAyABKAhSF2dvcHJvdG9FeHRlbnNpb25zTWFwQ
  WxsOlgKGGdvcHJvdG9fdW5yZWNvZ25pemVkX2FsbBIcLmdvb2dsZS5wcm90b2J1Zi5GaWxlT3B0aW9ucxiy7AMgASgIUhZnb3Byb
  3RvVW5yZWNvZ25pemVkQWxsOkkKEGdvZ29wcm90b19pbXBvcnQSHC5nb29nbGUucHJvdG9idWYuRmlsZU9wdGlvbnMYs+wDIAEoC
  FIPZ29nb3Byb3RvSW1wb3J0OkUKDnByb3Rvc2l6ZXJfYWxsEhwuZ29vZ2xlLnByb3RvYnVmLkZpbGVPcHRpb25zGLTsAyABKAhSD
  XByb3Rvc2l6ZXJBbGw6PwoLY29tcGFyZV9hbGwSHC5nb29nbGUucHJvdG9idWYuRmlsZU9wdGlvbnMYtewDIAEoCFIKY29tcGFyZ
  UFsbDpBCgx0eXBlZGVjbF9hbGwSHC5nb29nbGUucHJvdG9idWYuRmlsZU9wdGlvbnMYtuwDIAEoCFILdHlwZWRlY2xBbGw6QQoMZ
  W51bWRlY2xfYWxsEhwuZ29vZ2xlLnByb3RvYnVmLkZpbGVPcHRpb25zGLfsAyABKAhSC2VudW1kZWNsQWxsOlEKFGdvcHJvdG9fc
  mVnaXN0cmF0aW9uEhwuZ29vZ2xlLnByb3RvYnVmLkZpbGVPcHRpb25zGLjsAyABKAhSE2dvcHJvdG9SZWdpc3RyYXRpb246SgoPZ
  29wcm90b19nZXR0ZXJzEh8uZ29vZ2xlLnByb3RvYnVmLk1lc3NhZ2VPcHRpb25zGIH0AyABKAhSDmdvcHJvdG9HZXR0ZXJzOkwKE
  GdvcHJvdG9fc3RyaW5nZXISHy5nb29nbGUucHJvdG9idWYuTWVzc2FnZU9wdGlvbnMYg/QDIAEoCFIPZ29wcm90b1N0cmluZ2VyO
  kYKDXZlcmJvc2VfZXF1YWwSHy5nb29nbGUucHJvdG9idWYuTWVzc2FnZU9wdGlvbnMYhPQDIAEoCFIMdmVyYm9zZUVxdWFsOjUKB
  GZhY2USHy5nb29nbGUucHJvdG9idWYuTWVzc2FnZU9wdGlvbnMYhfQDIAEoCFIEZmFjZTo9Cghnb3N0cmluZxIfLmdvb2dsZS5wc
  m90b2J1Zi5NZXNzYWdlT3B0aW9ucxiG9AMgASgIUghnb3N0cmluZzo9Cghwb3B1bGF0ZRIfLmdvb2dsZS5wcm90b2J1Zi5NZXNzY
  WdlT3B0aW9ucxiH9AMgASgIUghwb3B1bGF0ZTo9CghzdHJpbmdlchIfLmdvb2dsZS5wcm90b2J1Zi5NZXNzYWdlT3B0aW9ucxjAi
  wQgASgIUghzdHJpbmdlcjo7Cgdvbmx5b25lEh8uZ29vZ2xlLnByb3RvYnVmLk1lc3NhZ2VPcHRpb25zGIn0AyABKAhSB29ubHlvb
  mU6NwoFZXF1YWwSHy5nb29nbGUucHJvdG9idWYuTWVzc2FnZU9wdGlvbnMYjfQDIAEoCFIFZXF1YWw6QwoLZGVzY3JpcHRpb24SH
  y5nb29nbGUucHJvdG9idWYuTWVzc2FnZU9wdGlvbnMYjvQDIAEoCFILZGVzY3JpcHRpb246OwoHdGVzdGdlbhIfLmdvb2dsZS5wc
  m90b2J1Zi5NZXNzYWdlT3B0aW9ucxiP9AMgASgIUgd0ZXN0Z2VuOj0KCGJlbmNoZ2VuEh8uZ29vZ2xlLnByb3RvYnVmLk1lc3NhZ
  2VPcHRpb25zGJD0AyABKAhSCGJlbmNoZ2VuOj8KCW1hcnNoYWxlchIfLmdvb2dsZS5wcm90b2J1Zi5NZXNzYWdlT3B0aW9ucxiR9
  AMgASgIUgltYXJzaGFsZXI6QwoLdW5tYXJzaGFsZXISHy5nb29nbGUucHJvdG9idWYuTWVzc2FnZU9wdGlvbnMYkvQDIAEoCFILd
  W5tYXJzaGFsZXI6TAoQc3RhYmxlX21hcnNoYWxlchIfLmdvb2dsZS5wcm90b2J1Zi5NZXNzYWdlT3B0aW9ucxiT9AMgASgIUg9zd
  GFibGVNYXJzaGFsZXI6NwoFc2l6ZXISHy5nb29nbGUucHJvdG9idWYuTWVzc2FnZU9wdGlvbnMYlPQDIAEoCFIFc2l6ZXI6TAoQd
  W5zYWZlX21hcnNoYWxlchIfLmdvb2dsZS5wcm90b2J1Zi5NZXNzYWdlT3B0aW9ucxiX9AMgASgIUg91bnNhZmVNYXJzaGFsZXI6U
  AoSdW5zYWZlX3VubWFyc2hhbGVyEh8uZ29vZ2xlLnByb3RvYnVmLk1lc3NhZ2VPcHRpb25zGJj0AyABKAhSEXVuc2FmZVVubWFyc
  2hhbGVyOlcKFmdvcHJvdG9fZXh0ZW5zaW9uc19tYXASHy5nb29nbGUucHJvdG9idWYuTWVzc2FnZU9wdGlvbnMYmfQDIAEoCFIUZ
  29wcm90b0V4dGVuc2lvbnNNYXA6VAoUZ29wcm90b191bnJlY29nbml6ZWQSHy5nb29nbGUucHJvdG9idWYuTWVzc2FnZU9wdGlvb
  nMYmvQDIAEoCFITZ29wcm90b1VucmVjb2duaXplZDpBCgpwcm90b3NpemVyEh8uZ29vZ2xlLnByb3RvYnVmLk1lc3NhZ2VPcHRpb
  25zGJz0AyABKAhSCnByb3Rvc2l6ZXI6OwoHY29tcGFyZRIfLmdvb2dsZS5wcm90b2J1Zi5NZXNzYWdlT3B0aW9ucxid9AMgASgIU
  gdjb21wYXJlOj0KCHR5cGVkZWNsEh8uZ29vZ2xlLnByb3RvYnVmLk1lc3NhZ2VPcHRpb25zGJ70AyABKAhSCHR5cGVkZWNsOjsKC
  G51bGxhYmxlEh0uZ29vZ2xlLnByb3RvYnVmLkZpZWxkT3B0aW9ucxjp+wMgASgIUghudWxsYWJsZTo1CgVlbWJlZBIdLmdvb2dsZ
  S5wcm90b2J1Zi5GaWVsZE9wdGlvbnMY6vsDIAEoCFIFZW1iZWQ6PwoKY3VzdG9tdHlwZRIdLmdvb2dsZS5wcm90b2J1Zi5GaWVsZ
  E9wdGlvbnMY6/sDIAEoCVIKY3VzdG9tdHlwZTo/CgpjdXN0b21uYW1lEh0uZ29vZ2xlLnByb3RvYnVmLkZpZWxkT3B0aW9ucxjs+
  wMgASgJUgpjdXN0b21uYW1lOjkKB2pzb250YWcSHS5nb29nbGUucHJvdG9idWYuRmllbGRPcHRpb25zGO37AyABKAlSB2pzb250Y
  Wc6OwoIbW9yZXRhZ3MSHS5nb29nbGUucHJvdG9idWYuRmllbGRPcHRpb25zGO77AyABKAlSCG1vcmV0YWdzOjsKCGNhc3R0eXBlE
  h0uZ29vZ2xlLnByb3RvYnVmLkZpZWxkT3B0aW9ucxjv+wMgASgJUghjYXN0dHlwZTo5CgdjYXN0a2V5Eh0uZ29vZ2xlLnByb3RvY
  nVmLkZpZWxkT3B0aW9ucxjw+wMgASgJUgdjYXN0a2V5Oj0KCWNhc3R2YWx1ZRIdLmdvb2dsZS5wcm90b2J1Zi5GaWVsZE9wdGlvb
  nMY8fsDIAEoCVIJY2FzdHZhbHVlOjkKB3N0ZHRpbWUSHS5nb29nbGUucHJvdG9idWYuRmllbGRPcHRpb25zGPL7AyABKAhSB3N0Z
  HRpbWU6QQoLc3RkZHVyYXRpb24SHS5nb29nbGUucHJvdG9idWYuRmllbGRPcHRpb25zGPP7AyABKAhSC3N0ZGR1cmF0aW9uQiEKE
  2NvbS5nb29nbGUucHJvdG9idWZCCkdvR29Qcm90b3M="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
      com.google.protobuf.descriptor.DescriptorProtoCompanion.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
  val goprotoEnumPrefix: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.EnumOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(62001, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val goprotoEnumStringer: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.EnumOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(62021, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val enumStringer: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.EnumOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(62022, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val enumCustomname: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.EnumOptions, scala.Option[_root_.scala.Predef.String]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(62023, _root_.scalapb.UnknownFieldSet.Field.lengthDelimitedLens)({__valueIn => __valueIn.toStringUtf8}, {__valueIn => _root_.com.google.protobuf.ByteString.copyFromUtf8(__valueIn)})
  val enumdecl: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.EnumOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(62024, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val enumvalueCustomname: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.EnumValueOptions, scala.Option[_root_.scala.Predef.String]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(66001, _root_.scalapb.UnknownFieldSet.Field.lengthDelimitedLens)({__valueIn => __valueIn.toStringUtf8}, {__valueIn => _root_.com.google.protobuf.ByteString.copyFromUtf8(__valueIn)})
  val goprotoGettersAll: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FileOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(63001, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val goprotoEnumPrefixAll: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FileOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(63002, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val goprotoStringerAll: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FileOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(63003, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val verboseEqualAll: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FileOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(63004, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val faceAll: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FileOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(63005, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val gostringAll: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FileOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(63006, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val populateAll: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FileOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(63007, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val stringerAll: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FileOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(63008, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val onlyoneAll: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FileOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(63009, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val equalAll: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FileOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(63013, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val descriptionAll: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FileOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(63014, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val testgenAll: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FileOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(63015, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val benchgenAll: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FileOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(63016, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val marshalerAll: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FileOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(63017, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val unmarshalerAll: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FileOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(63018, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val stableMarshalerAll: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FileOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(63019, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val sizerAll: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FileOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(63020, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val goprotoEnumStringerAll: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FileOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(63021, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val enumStringerAll: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FileOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(63022, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val unsafeMarshalerAll: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FileOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(63023, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val unsafeUnmarshalerAll: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FileOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(63024, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val goprotoExtensionsMapAll: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FileOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(63025, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val goprotoUnrecognizedAll: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FileOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(63026, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val gogoprotoImport: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FileOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(63027, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val protosizerAll: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FileOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(63028, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val compareAll: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FileOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(63029, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val typedeclAll: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FileOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(63030, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val enumdeclAll: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FileOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(63031, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val goprotoRegistration: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FileOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(63032, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val goprotoGetters: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.MessageOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(64001, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val goprotoStringer: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.MessageOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(64003, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val verboseEqual: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.MessageOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(64004, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val face: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.MessageOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(64005, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val gostring: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.MessageOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(64006, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val populate: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.MessageOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(64007, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val stringer: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.MessageOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(67008, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val onlyone: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.MessageOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(64009, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val equal: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.MessageOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(64013, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val description: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.MessageOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(64014, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val testgen: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.MessageOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(64015, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val benchgen: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.MessageOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(64016, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val marshaler: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.MessageOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(64017, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val unmarshaler: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.MessageOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(64018, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val stableMarshaler: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.MessageOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(64019, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val sizer: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.MessageOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(64020, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val unsafeMarshaler: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.MessageOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(64023, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val unsafeUnmarshaler: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.MessageOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(64024, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val goprotoExtensionsMap: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.MessageOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(64025, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val goprotoUnrecognized: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.MessageOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(64026, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val protosizer: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.MessageOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(64028, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val compare: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.MessageOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(64029, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val typedecl: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.MessageOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(64030, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val nullable: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FieldOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(65001, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val embed: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FieldOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(65002, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val customtype: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FieldOptions, scala.Option[_root_.scala.Predef.String]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(65003, _root_.scalapb.UnknownFieldSet.Field.lengthDelimitedLens)({__valueIn => __valueIn.toStringUtf8}, {__valueIn => _root_.com.google.protobuf.ByteString.copyFromUtf8(__valueIn)})
  val customname: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FieldOptions, scala.Option[_root_.scala.Predef.String]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(65004, _root_.scalapb.UnknownFieldSet.Field.lengthDelimitedLens)({__valueIn => __valueIn.toStringUtf8}, {__valueIn => _root_.com.google.protobuf.ByteString.copyFromUtf8(__valueIn)})
  val jsontag: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FieldOptions, scala.Option[_root_.scala.Predef.String]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(65005, _root_.scalapb.UnknownFieldSet.Field.lengthDelimitedLens)({__valueIn => __valueIn.toStringUtf8}, {__valueIn => _root_.com.google.protobuf.ByteString.copyFromUtf8(__valueIn)})
  val moretags: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FieldOptions, scala.Option[_root_.scala.Predef.String]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(65006, _root_.scalapb.UnknownFieldSet.Field.lengthDelimitedLens)({__valueIn => __valueIn.toStringUtf8}, {__valueIn => _root_.com.google.protobuf.ByteString.copyFromUtf8(__valueIn)})
  val casttype: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FieldOptions, scala.Option[_root_.scala.Predef.String]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(65007, _root_.scalapb.UnknownFieldSet.Field.lengthDelimitedLens)({__valueIn => __valueIn.toStringUtf8}, {__valueIn => _root_.com.google.protobuf.ByteString.copyFromUtf8(__valueIn)})
  val castkey: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FieldOptions, scala.Option[_root_.scala.Predef.String]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(65008, _root_.scalapb.UnknownFieldSet.Field.lengthDelimitedLens)({__valueIn => __valueIn.toStringUtf8}, {__valueIn => _root_.com.google.protobuf.ByteString.copyFromUtf8(__valueIn)})
  val castvalue: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FieldOptions, scala.Option[_root_.scala.Predef.String]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(65009, _root_.scalapb.UnknownFieldSet.Field.lengthDelimitedLens)({__valueIn => __valueIn.toStringUtf8}, {__valueIn => _root_.com.google.protobuf.ByteString.copyFromUtf8(__valueIn)})
  val stdtime: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FieldOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(65010, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
  val stdduration: _root_.scalapb.GeneratedExtension[com.google.protobuf.descriptor.FieldOptions, scala.Option[_root_.scala.Boolean]] =
    _root_.scalapb.GeneratedExtension.forOptionalUnknownField(65011, _root_.scalapb.UnknownFieldSet.Field.varintLens)({__valueIn => __valueIn != 0}, {__valueIn => _root_.scalapb.GeneratedExtension.Internal.bool2Long(__valueIn)})
}